### ISSUE TITLE
Idea: Break if `.Fold` ends up with `TError`

### ISSUE THREAD

**Issue by chartjunk** [Resultful/Resultful#2]
Please provide a way to `break` away from `.Fold` once the first `TError` is yield. This would be useful when the whole source `IEnumerable<Result<T, TError>>` is not necessary/wanted to be enumerated if an error has occured.

Either provide an overload without the `mergeFunc` parameter or provide a new extension called `.FoldBreak` or similar.

**Comment by rtkelly13** [comment]
This is a great suggestion, the name I would suggest is probably `FoldUntil`, shouldn't be too hard to implement. Not sure how the early fail would work, would probably need a recursive implementation for that.
A naive one that iterates over everything and calls map on the Seed value.

Might not make it into 0.2.0 but would be a great addition to a 0.2.1/0.3.0.
Happy to accept a PR obviously!

**Comment by chartjunk** [comment]
How about a pattern like this?
```c#
public static Result<TResult, TError> FoldUntil<TResult, T, TError>(this IEnumerable<Result<T, TError>> values,
	TResult seed, Func<TResult, T, TResult> aggrFunc)
	=> values.FoldUntil(seed.Ok<TResult, TError>(), aggrFunc);

public static Result<TResult, TError> FoldUntil<TResult, T, TError>(this IEnumerable<Result<T, TError>> values,
	Result<TResult, TError> seed, Func<TResult, T, TResult> aggrFunc)
	=> values.TakeUntil(IsError).Fold(seed, (e, _) => e, aggrFunc: aggrFunc);

public static IEnumerable<TSource> TakeUntil<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
{
	foreach (var i in source)
	{
		yield return i;
		if (predicate(i))
			yield break;
	}
}

public static bool IsError<T, TError>(this Result<T, TError> result)
	=> result.Match(_ => false, _ => true);
```

**Comment by rtkelly13** [comment]
Yeah that is on the right lines! I guess it all depends on if the list should be evaluated twice in the worst case.

You had me interested in this so I have started on a branch, need to push it up tomorrow if you are interested in reviewing it?

I need to make sure the whole API set has coverage. But IsError/IsOk would be expected additions too.

**Comment by rtkelly13** [comment]
I may implement a FoldUntil over `IEnumerable<T>` where the Accumulator function returns Option<TResult> and when None is present terminate! This could be used as a basis for the Result FoldUntil implementation where the number of items evaluated would be Error index + 1 or number of items whichever is lower!

**Comment by chartjunk** [comment]
@rtkelly13 Sure, I'll review your PR!

**Comment by rtkelly13** [comment]
Solved with https://github.com/Resultful/Resultful/pull/4
