### ISSUE TITLE
`.Tee` for errors

### ISSUE THREAD

**Issue by chartjunk** [Resultful/Resultful#3]
Please provide `.Tee`-like functionality for errors. E.g. `.TeeError`.

**Comment by rtkelly13** [comment]
This does exist!
https://github.com/Resultful/Resultful/blob/master/Resultful/Result.cs#L103

I'm not sure if it has hit nuget yet though,
Lost some of the CI pipline as part of the project rename.
Still evaluating if I want to use Azure Pipelines or stick with Travis CI

This will be out with a 0.2.0 release
I will put a preview under the new project name at some point!
