### ISSUE TITLE
Support applying Options onto "Normal world" objects

### ISSUE THREAD

**Issue by chartjunk** [Resultful/Resultful#8]
### Idea
Tbh, I'm not sure if `apply` is the correct word here, but the idea is the following: it would be very beneficial if `Option<O>` could be applied onto Normal world object of type `N` conditionally:
* If `Option<O>` is `Some`, then apply using `Func<N, O, N>`
* If `Option<O>` is `None`, then do nothing to the Normal world object.
### Example
```c#
public class LoggingSetup
{
   public Option<ConsoleLoggingSetup> ConsoleLoggingSetup { get; }
   public Option<FileLoggingSetup> FileLoggingSetup { get; }
}
public Logger ConfigureLogging(Logger logger, LoggingSetup setup)
{
   return logger
      .ApplyOption(setup.ConsoleLoggingSetup, (l, cls) => l.SinkToConsole(cls))
      .ApplyOption(setup.FileLoggingSetup, (l, fls) => l.SinkToFile(fls));
}
```
### Implementation
is very simple:
```c#
   public static N ApplyOption<N, O>(this N target, Option<O> option, Func<N, O, N> apply)
      => option.Match(s => apply(target, s), n => target);
```

I could create a PR for this, but not 100% sure about naming.

**Comment by rtkelly13** [comment]
Looking into this seems like the name is Fold!
https://msdn.microsoft.com/visualfsharpdocs/conceptual/option.fold%5b%27t%2c%27state%5d-function-%5bfsharp%5d

You could provide this in two ways F# provides a Fold and FoldBack method where the arguments are swapped around, maybe both could be implemented for Option here one as an extension method, the other as an instance member?

**Comment by rtkelly13** [comment]
Solved by https://github.com/Resultful/Resultful/pull/9
